field.widget.settings.link_attributes_field_widget:
  type: mapping
  label: 'Link Attributes settings'
  mapping:
    placeholder_title:
      type: label
      label: 'Placeholder for link attribute'
